
fix/style:
	"$(BIN_ECHO)" "Fixing style issues on Keqing..."

build/release:
	"$(BIN_ECHO)" "Building Keqing to target 'release'..."
	"$(BIN_ECHO)" "BUILT_BINARY" > "$(ARG_ARTIFACT_ROOT)/keqing.txt"

test/unit:
	"$(BIN_ECHO)" "Executing unit tests on Keqing..."

style/lint:
	"$(BIN_ECHO)" "Linting subproject Keqing..."

clean:
	"$(BIN_ECHO)" "Cleaning temporary files on Keqing..."
